AWSTemplateFormatVersion: "2010-09-09"
Description: "Development environment resources for the Direct Research Dashboard"

Parameters:
  ParticipantUserPoolName:
    Type: String
    Description: Name of the participant user pool

  ParticipantUserPoolDomainName:
    Type: String
    Description: Domain name of the participant user pool

  ResearcherUserPoolName:
    Type: String
    Description: Name of the researcher user pool

  ResearcherUserPoolDomainName:
    Type: String
    Description: Domain name of the researcher user pool

  LogsBucketName:
    Type: String
    Description: Name of the logs bucket

  AudioBucketName:
    Type: String
    Description: Name of the audio bucket

  TokensSecretName:
    Type: String
    Description: Name of the tokens secret

  SecretName:
    Type: String
    Description: Name of the secret

Resources:
  ParticipantUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref ParticipantUserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      AliasAttributes:
        - preferred_username
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1

  ParticipantUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref ParticipantUserPoolDomainName
      UserPoolId: !Ref ParticipantUserPool

  ParticipantUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ParticipantUserPool
      GenerateSecret: true
      CallbackURLs:
        - http://localhost:5000/auth/participant/callback
      LogoutURLs:
        - http://localhost:3000/login
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true

  ResearcherUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref ResearcherUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: given_name
          AttributeDataType: String
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - phone_number
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameConfiguration:
        CaseSensitive: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  ResearcherUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref ResearcherUserPoolDomainName
      UserPoolId: !Ref ResearcherUserPool

  ResearcherUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ResearcherUserPool
      GenerateSecret: true
      CallbackURLs:
        - http://localhost:5000/auth/researcher/callback
      LogoutURLs:
        - http://localhost:3000/coordinator/login
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - phone
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogsBucketName
      VersioningConfiguration:
        Status: Enabled

  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AudioBucketName
      VersioningConfiguration:
        Status: Enabled

  DevSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName

  TokensSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref TokensSecretName
      SecretString: "{}"

Outputs:
  ParticipantUserPoolId:
    Description: ID of the participant user pool
    Value: !Ref ParticipantUserPool

  ParticipantClientId:
    Description: Client ID of the participant user pool client
    Value: !Ref ParticipantUserPoolClient

  ResearcherUserPoolId:
    Description: ID of the researcher user pool
    Value: !Ref ResearcherUserPool

  ResearcherClientId:
    Description: Client ID of the researcher user pool client
    Value: !Ref ResearcherUserPoolClient
