AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda dev execution roles."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Config
        Parameters:
          - App
          - Username
      - Label:
          default: Wearable Data Retrieval Config
        Parameters:
          - WearableDataRetrievalLogsBucketName

    ParameterLabels:
      App:
        default: App
      Username:
        default: Username
      WearableDataRetrievalLogsBucketName:
        default: Wearable Data Retrieval Log Bucket Name

Parameters:
  App:
    Type: String
    Default: ditti-dashboard
    Description: App name

  Username:
    Type: String
    Description: Username to create dev execution role for

  WearableDataRetrievalLogsBucketName:
    Type: String
    Description: Name of the Wearable Data Retrieval log bucket

Resources:
  WearableDataRetrievalLambdaDevRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Username}-wearable-data-retrieval-lambda-dev-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/${Username}"
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "wearable-data-retrieval-lambda-dev-role-logs-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${WearableDataRetrievalLogsBucketName}/*"

Outputs:
  WearableDataRetrievalLambdaDevRoleARN:
    Value: !GetAtt WearableDataRetrievalLambdaDevRole.Arn
    Export:
      Name: !Sub "${App}-${Username}-wearable-data-retrieval-lambda-dev-role-arn"
