# Copyright 2025 The Trustees of the University of Pennsylvania
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may]
# not use this file except in compliance with the License. You may obtain a
# copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda functions for the application."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Config
        Parameters:
          - App
          - Environment
          - IAMStackName
          - VpcStackName
          - RDSStackName
          - AppFunctionName
          - AppInvocationURL
      - Label:
          default: Fitbit
        Parameters:
          - FitbitSecretName
          - FitbitTokensSecretName
      - Label:
          default: Wearable Data Retrieval
        Parameters:
          - WearableDataRetrievalImageURI
          - WearableDataRetrievalLogsBucketName
          - WearableDataRetrievalLogLevel
          - WearableDataRetrievalDailyTriggerSchedule
      - Label:
          default: Flask Secret Key Rotator
        Parameters:
          - FlaskSecretKeyRotatorImageURI
          - FlaskSecretKeyRotatorSecretName
          - FlaskSecretKeyRotatorDays

    ParameterLabels:
      App:
        default: App
      Environment:
        default: Environment
      IAMStackName:
        default: IAM Stack Name
      VpcStackName:
        default: VPC Stack Name
      RDSStackName:
        default: RDS Stack Name
      AppInvocationURL:
        default: App Invocation URL
      AppFunctionName:
        default: App Function Name
      FitbitSecretName:
        default: Fitbit Secret Name
      FitbitTokensSecretName:
        default: Fitbit Tokens Secret Name
      WearableDataRetrievalImageURI:
        default: Image URI
      WearableDataRetrievalLogsBucketName:
        default: Logs Bucket Name
      WearableDataRetrievalLogLevel:
        default: Log Level
      WearableDataRetrievalDailyTriggerSchedule:
        default: Daily Trigger Schedule
      FlaskSecretKeyRotatorImageURI:
        default: Image URI
      FlaskSecretKeyRotatorSecretName:
        default: Flask Secret Key Secret Name
      FlaskSecretKeyRotatorDays:
        default: Rotate Automatically After Days

Parameters:
  App:
    Type: String
    Default: ditti-dashboard
    Description: App name

  Environment:
    Type: String
    AllowedValues:
      - staging
      - prod
    Description: Environment name

  IAMStackName:
    Type: String
    Description: Name of the IAM stack to import resources from

  VpcStackName:
    Type: String
    Description: Name of the VPC stack to import resources from

  RDSStackName:
    Type: String
    Description: Name of the RDS stack to import resources from

  AppInvocationURL:
    Type: String
    Description: URL of the Flask application to invoke the secret key rotator function

  AppFunctionName:
    Type: String
    Description: Name of the Flask application function

  FitbitSecretName:
    Type: String
    Description: Name of the Fitbit secret

  FitbitTokensSecretName:
    Type: String
    Description: Name of the Fitbit tokens secret

  WearableDataRetrievalImageURI:
    Type: String
    Description: URI of the Wearable Data Retrieval image

  WearableDataRetrievalLogsBucketName:
    Type: String
    Description: Name of the Wearable Data Retrieval logs bucket

  WearableDataRetrievalLogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - TRACE
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - FATAL
    Description: Application log level for the Wearable Data Retrieval Lambda function

  WearableDataRetrievalDailyTriggerSchedule:
    Type: String
    Default: "cron(0 0 * * ? *)"
    Description: Schedule expression for the Wearable Data Retrieval daily trigger

  FlaskSecretKeyRotatorImageURI:
    Type: String
    Description: URI of the Flask Secret Key Rotator image

  FlaskSecretKeyRotatorSecretName:
    Type: String
    Description: Name of the Flask secret key secret

  FlaskSecretKeyRotatorDays:
    Type: Number
    Default: 14
    Description: Number of days after which to rotate the Flask secret key

Resources:

  ###########################
  # Wearable Data Retrieval #
  ###########################
  WearableDataRetrievalSecretAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "wearable-data-retrieval-lambda-role-secret-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "secretsmanager:*"
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${FitbitSecretName}*"
          - Effect: "Allow"
            Action: "secretsmanager:*"
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${FitbitTokensSecretName}*"
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-WearableDataRetrievalLambdaRoleName

  WearableDataRetrievalLogsAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "wearable-data-retrieval-lambda-role-logs-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${WearableDataRetrievalLogsBucketName}/*"
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-WearableDataRetrievalLambdaRoleName

  WearableDataRetrievalRDSIAMAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "wearable-data-retrieval-lambda-role-rds-iam"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "rds-db:connect"
            Resource:
              - Fn::ImportValue: !Sub ${RDSStackName}-IAMUserARN
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-WearableDataRetrievalLambdaRoleName

  WearableDataRetrievalLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-wearable-data-retrieval-${Environment}"
      Architectures:
        - x86_64
      Code:
        ImageUri: !Ref WearableDataRetrievalImageURI
      MemorySize: 512
      PackageType: Image
      Role:
        Fn::ImportValue: !Sub ${IAMStackName}-WearableDataRetrievalLambdaRoleArn
      Timeout: 180
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-LambdaSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet2
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref WearableDataRetrievalLogsBucketName
          DB_URI:
            Fn::ImportValue: !Sub ${RDSStackName}-DBClusterIamUrl
          DB_USE_IAM: "true"
          FITBIT_SECRET_NAME: !Ref FitbitSecretName
          FITBIT_TOKENS_SECRET_NAME: !Ref FitbitTokensSecretName
          LOG_LEVEL: !Ref WearableDataRetrievalLogLevel
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Environment
          Value: !Ref Environment

  WearableDataRetrievalDailyTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${App}-wearable-data-retrieval-daily-${Environment}"
      Description: "Triggers wearable data retrieval function daily at midnight"
      ScheduleExpression: !Ref WearableDataRetrievalDailyTriggerSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt WearableDataRetrievalLambdaFunction.Arn
          Id: "WearableDataRetrievalTarget"

  WearableDataRetrievalLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WearableDataRetrievalLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt WearableDataRetrievalDailyTrigger.Arn

  ############################
  # Flask Secret Key Rotator #
  ############################
  FlaskSecretKeyRotatorSecretsAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "flask-secret-key-rotator-lambda-role-secrets-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:GetSecretValue"
              - "secretsmanager:PutSecretValue"
              - "secretsmanager:UpdateSecretVersionStage"
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${FlaskSecretKeyRotatorSecretName}*"
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-FlaskSecretKeyRotatorLambdaRoleName

  FlaskSecretKeyRotatorRandomPasswordAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "flask-secret-key-rotator-lambda-role-random-password-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "secretsmanager:GetRandomPassword"
            Resource: "*"
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-FlaskSecretKeyRotatorLambdaRoleName

  FlaskSecretKeyRotatorLambdaAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "flask-secret-key-rotator-lambda-role-lambda-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "lambda:UpdateFunctionConfiguration"
              - "lambda:GetFunctionConfiguration"
              - "lambda:GetFunction"
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AppFunctionName}*"
      RoleName:
        Fn::ImportValue: !Sub ${IAMStackName}-FlaskSecretKeyRotatorLambdaRoleName

  FlaskSecretKeyRotatorLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${App}-flask-secret-key-rotator-${Environment}"
      Architectures:
        - x86_64
      Code:
        ImageUri: !Ref FlaskSecretKeyRotatorImageURI
      MemorySize: 512
      PackageType: Image
      Role:
        Fn::ImportValue: !Sub ${IAMStackName}-FlaskSecretKeyRotatorLambdaRoleArn
      Timeout: 180
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-LambdaSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet2
      Environment:
        Variables:
          APP_LAMBDA_FUNCTION_NAME: !Ref AppFunctionName
          APP_URL: !Ref AppInvocationURL
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Environment
          Value: !Ref Environment

  FlaskSecretKeyRotatorRotationSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FlaskSecretKeyRotatorLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "secretsmanager.amazonaws.com"
      SourceAccount: !Ref AWS::AccountId

  FlaskSecretKeyRotatorRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: FlaskSecretKeyRotatorRotationSchedulePermission
    Properties:
      RotationLambdaARN: !GetAtt FlaskSecretKeyRotatorLambdaFunction.Arn
      RotationRules:
        AutomaticallyAfterDays: !Ref FlaskSecretKeyRotatorDays
      SecretId: !Ref FlaskSecretKeyRotatorSecretName

Outputs:
  FlaskSecretKeyRotatorLambdaFunctionName:
    Value: !Ref FlaskSecretKeyRotatorLambdaFunction
  FlaskSecretKeyRotatorImageUri:
    Value: !Ref FlaskSecretKeyRotatorImageURI
  WearableDataRetrievalLambdaFunctionName:
    Value: !Ref WearableDataRetrievalLambdaFunction
  WearableDataRetrievalImageUri:
    Value: !Ref WearableDataRetrievalImageURI
