AWSTemplateFormatVersion: "2010-09-09"
Description: "Application IAM roles"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      App:
        default: App Name
      PrincipalUserArns:
        default: Principals

Parameters:
  App:
    Type: String
    Default: ditti-dashboard
    Description: App name
  PrincipalUserArns:
    Type: String
    Description: User ARNs to override default role principals for (optional) (e.g. arn:aws:iam::123456789012:user/user1,arn:aws:iam::123456789012:user/user2).

Conditions:
  OverridePrincipals: !Not [!Equals [!Ref PrincipalUserArns, ""]]

Resources:
  DBBootStrapLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: !If
              - OverridePrincipals
              - AWS: !Split [",", !Ref PrincipalUserArns]
              - Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

  FlaskSecretKeyRotatorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: !If
              - OverridePrincipals
              - AWS: !Split [",", !Ref PrincipalUserArns]
              - Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

  WearableDataRetrievalLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: !If
              - OverridePrincipals
              - AWS: !Split [",", !Ref PrincipalUserArns]
              - Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

Outputs:
  DBBootStrapLambdaRoleArn:
    Value: !GetAtt DBBootStrapLambdaRole.Arn
  FlaskSecretKeyRotatorLambdaRoleArn:
    Value: !GetAtt FlaskSecretKeyRotatorLambdaRole.Arn
  WearableDataRetrievalLambdaRoleArn:
    Value: !GetAtt WearableDataRetrievalLambdaRole.Arn
