# Copyright 2025 The Trustees of the University of Pennsylvania
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may]
# not use this file except in compliance with the License. You may obtain a
# copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

AWSTemplateFormatVersion: "2010-09-09"
Description: "Application IAM roles"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      App:
        default: App Name
      Environment:
        default: Environment

Parameters:
  App:
    Type: String
    Default: ditti-dashboard
    Description: App name
  Environment:
    Type: String
    AllowedValues:
      - staging
      - prod
    Description: Environment

Resources:
  DBBootStrapLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Environment}-db-bootstrap-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

  FlaskSecretKeyRotatorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Environment}-flask-secret-key-rotator-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

  WearableDataRetrievalLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${App}-${Environment}-wearable-data-retrieval-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"

Outputs:
  DBBootStrapLambdaRoleArn:
    Description: ARN of the DB bootstrap Lambda role
    Value: !GetAtt DBBootStrapLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DBBootStrapLambdaRoleArn"
  DBBootStrapLambdaRoleName:
    Description: Name of the DB bootstrap Lambda role
    Value: !Ref DBBootStrapLambdaRole
    Export:
      Name: !Sub "${AWS::StackName}-DBBootStrapLambdaRoleName"
  FlaskSecretKeyRotatorLambdaRoleArn:
    Description: ARN of the Flask secret key rotator Lambda role
    Value: !GetAtt FlaskSecretKeyRotatorLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FlaskSecretKeyRotatorLambdaRoleArn"
  FlaskSecretKeyRotatorLambdaRoleName:
    Description: Name of the Flask secret key rotator Lambda role
    Value: !Ref FlaskSecretKeyRotatorLambdaRole
    Export:
      Name: !Sub "${AWS::StackName}-FlaskSecretKeyRotatorLambdaRoleName"
  WearableDataRetrievalLambdaRoleArn:
    Description: ARN of the wearable data retrieval Lambda role
    Value: !GetAtt WearableDataRetrievalLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WearableDataRetrievalLambdaRoleArn"
  WearableDataRetrievalLambdaRoleName:
    Description: Name of the wearable data retrieval Lambda role
    Value: !Ref WearableDataRetrievalLambdaRole
    Export:
      Name: !Sub "${AWS::StackName}-WearableDataRetrievalLambdaRoleName"
