name: Other Issue
description: A general template for other issues
title: "[Other]"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Other Issues
        Use this form for any issues that do not fit in bug reports or feature requests.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a description of your issue."
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: "What is the impact of this issue?"
      multiple: false
      options:
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues (if applicable)
      description: "List any related GitHub issues."
      placeholder: |
        - Related to #Issue
