import nh3


def sanitize_quill_html(html: str) -> str:
    """Sanitize QuillJS HTML output using nh3 configuration.

    This function cleans the HTML generated by the Quill editor. It enforces a strict set
    of allowed tags, attributes, and CSS classes to preserve Quill's rich formatting while
    protecting against unsafe content injection.
    """

    # Define the set of HTML tags that are permitted.
    allowed_tags = {
        "a", "blockquote", "br", "div", "em", "h1", "h2", "h3", "h4", "h5", "h6",
        "iframe", "img", "li", "ol", "p", "pre", "span", "strong", "sub", "sup",
        "table", "tbody", "td", "tr", "ul", "select", "option", "u", "s"
    }

    # Map each tag to the set of allowed attributes.
    # Added entries for <u> and <s> so that underlined and strike-through text are preserved.
    attributes = {
        "div": {"class", "style", "spellcheck", "data-language"},
        "td": {"class", "style", "spellcheck", "data-row"},
        "li": {"class", "style", "spellcheck", "data-list"},
        "iframe": {"class", "style", "spellcheck", "allowfullscreen", "frameborder", "src"},
        "a": {"class", "style", "spellcheck", "href", "target"},
        "select": {"class", "style", "spellcheck", "contenteditable"},
        "option": {"class", "style", "spellcheck", "value"},
        "img": {"class", "style", "spellcheck", "src", "alt"},
        "p": {"class", "style", "spellcheck"},
        "span": {"class", "style", "spellcheck"},
        "h1": {"class", "style", "spellcheck"},
        "h2": {"class", "style", "spellcheck"},
        "h3": {"class", "style", "spellcheck"},
        "h4": {"class", "style", "spellcheck"},
        "h5": {"class", "style", "spellcheck"},
        "h6": {"class", "style", "spellcheck"},
        "blockquote": {"class", "style", "spellcheck"},
        "pre": {"class", "style", "spellcheck"},
        "ol": {"class", "style", "spellcheck"},
        "ul": {"class", "style", "spellcheck"},
        "table": {"class", "style", "spellcheck"},
        "tbody": {"class", "style", "spellcheck"},
        "tr": {"class", "style", "spellcheck"},
        "strong": {"class", "style", "spellcheck"},
        "em": {"class", "style", "spellcheck"},
        "sub": {"class", "style", "spellcheck"},
        "sup": {"class", "style", "spellcheck"},
        "br": {"class", "style", "spellcheck"},
        "u": {"class", "style", "spellcheck"},
        "s": {"class", "style", "spellcheck"}
    }

    # Define allowed CSS class names for specific tags.
    # This allowlist helps maintain the intended QuillJS formatting.
    class_allowlist = {
        "div": {
            "ql-code-block-container", "ql-code-block", "ql-token", "ql-ui",
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4",
            "ql-indent-5", "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9",
            "ql-size-small", "ql-size-large", "ql-size-huge", "ql-video"
        },
        "span": {
            "ql-token", "hljs-keyword", "hljs-number", "hljs-string", "hljs-comment",
            "hljs-function", "hljs-title", "hljs-params", "hljs-variable",
            "hljs-operator", "hljs-builtin"
        },
        "p": {
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4",
            "ql-indent-5", "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9"
        },
        "li": {
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4",
            "ql-indent-5", "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9"
        },
        "iframe": {"ql-video"},
        "td": {"ql-align-center", "ql-align-right", "ql-align-justify"},
        "select": {"ql-ui"},
        "tr": {"ql-align-center", "ql-align-right", "ql-align-justify"}
    }

    # Transform the class allowlist into the structure expected by nh3.
    tag_attribute_values = {
        tag: {"class": classes}
        for tag, classes in class_allowlist.items()
    }

    # Specify safe URL schemes for attributes like href or src.
    # This helps prevent unsafe protocols (e.g., "javascript:").
    url_schemes = {"http", "https", "mailto", "tel"}

    # Set the default link relationship attribute for security.
    # Even though 'rel' is not allowed in attributes for <a> tags here,
    # nh3 will apply this default value to maintain link safety.
    link_rel = "noopener noreferrer"

    return nh3.clean(
        html,
        tags=allowed_tags,
        attributes=attributes,
        url_schemes=url_schemes,
        link_rel=link_rel,
        tag_attribute_values=tag_attribute_values,
        clean_content_tags=set()
    )
