# Ditti Research Dashboard
# Copyright (C) 2025 the Trustees of the University of Pennsylvania
#
# Ditti Research Dashboard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Ditti Research Dashboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import nh3


def sanitize_quill_html(html: str) -> str:
    """Sanitize QuillJS HTML output using nh3 configuration.

    This function cleans the HTML generated by the Quill editor, preserving the intended
    formatting while stripping unsafe content.
    """

    allowed_tags = {
        "a", "blockquote", "br", "div", "em", "h1", "h2", "h3", "h4", "h5", "h6",
        "iframe", "img", "li", "ol", "p", "pre", "span", "strong", "sub", "sup",
        "table", "tbody", "td", "tr", "ul", "select", "option", "u", "s"
    }

    attributes = {
        "div": {"class", "style", "data-language"},
        "td": {"class", "style", "data-row"},
        "li": {"class", "style", "data-list"},
        "iframe": {"class", "style", "allowfullscreen", "frameborder", "src"},
        "a": {"class", "style", "href", "target"},
        "select": {"class", "style"},
        "option": {"class", "style", "value"},
        "img": {"class", "style", "src", "alt"},
        "p": {"class", "style"},
        "span": {"class", "style"},
        "h1": {"class", "style"},
        "h2": {"class", "style"},
        "h3": {"class", "style"},
        "h4": {"class", "style"},
        "h5": {"class", "style"},
        "h6": {"class", "style"},
        "blockquote": {"class", "style"},
        "pre": {"class", "style"},
        "ol": {"class", "style"},
        "ul": {"class", "style"},
        "table": {"class", "style"},
        "tbody": {"class", "style"},
        "tr": {"class", "style"},
        "strong": {"class", "style"},
        "em": {"class", "style"},
        "sub": {"class", "style"},
        "sup": {"class", "style"},
        "br": {"class", "style"},
        "u": {"class", "style"},
        "s": {"class", "style"}
    }

    class_allowlist = {
        "div": {
            "ql-code-block-container", "ql-code-block", "ql-token", "ql-ui",
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4", "ql-indent-5",
            "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9",
            "ql-size-small", "ql-size-large", "ql-size-huge", "ql-video"
        },
        "span": {
            "ql-token", "hljs-keyword", "hljs-number", "hljs-string", "hljs-comment",
            "hljs-function", "hljs-title", "hljs-params", "hljs-variable",
            "hljs-operator", "hljs-builtin", "ql-ui"  # "ql-ui" added here
        },
        "p": {
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4", "ql-indent-5",
            "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9"
        },
        "li": {
            "ql-align-center", "ql-align-right", "ql-align-justify",
            "ql-indent-1", "ql-indent-2", "ql-indent-3", "ql-indent-4", "ql-indent-5",
            "ql-indent-6", "ql-indent-7", "ql-indent-8", "ql-indent-9"
        },
        "iframe": {"ql-video"},
        "td": {"ql-align-center", "ql-align-right", "ql-align-justify"},
        "select": {"ql-ui"},
        "tr": {"ql-align-center", "ql-align-right", "ql-align-justify"}
    }

    # Transform the class allowlist into the structure expected by nh3.
    tag_attribute_values = {
        tag: {"class": classes}
        for tag, classes in class_allowlist.items()
    }

    url_schemes = {"http", "https", "mailto", "tel"}

    # Set the default link relationship attribute.
    link_rel = "noopener noreferrer"

    return nh3.clean(
        html,
        tags=allowed_tags,
        attributes=attributes,
        url_schemes=url_schemes,
        link_rel=link_rel,
        tag_attribute_values=tag_attribute_values,
        clean_content_tags=set()
    )
