# Copyright 2025 The Trustees of the University of Pennsylvania
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may]
# not use this file except in compliance with the License. You may obtain a
# copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import nh3


def sanitize_quill_html(html: str) -> str:
    """
    Sanitize QuillJS HTML output using nh3 configuration.

    This function cleans the HTML generated by the Quill editor,
    preserving the intended formatting while stripping unsafe content.
    """
    allowed_tags = {
        "a",
        "blockquote",
        "br",
        "div",
        "em",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "iframe",
        "img",
        "li",
        "ol",
        "p",
        "pre",
        "span",
        "strong",
        "sub",
        "sup",
        "table",
        "tbody",
        "td",
        "tr",
        "ul",
        "select",
        "option",
        "u",
        "s",
    }

    attributes = {
        "div": {"class", "style", "data-language"},
        "td": {"class", "style", "data-row"},
        "li": {"class", "style", "data-list"},
        "iframe": {"class", "style", "allowfullscreen", "frameborder", "src"},
        "a": {"class", "style", "href", "target"},
        "select": {"class", "style"},
        "option": {"class", "style", "value"},
        "img": {"class", "style", "src", "alt"},
        "p": {"class", "style"},
        "span": {"class", "style"},
        "h1": {"class", "style"},
        "h2": {"class", "style"},
        "h3": {"class", "style"},
        "h4": {"class", "style"},
        "h5": {"class", "style"},
        "h6": {"class", "style"},
        "blockquote": {"class", "style"},
        "pre": {"class", "style"},
        "ol": {"class", "style"},
        "ul": {"class", "style"},
        "table": {"class", "style"},
        "tbody": {"class", "style"},
        "tr": {"class", "style"},
        "strong": {"class", "style"},
        "em": {"class", "style"},
        "sub": {"class", "style"},
        "sup": {"class", "style"},
        "br": {"class", "style"},
        "u": {"class", "style"},
        "s": {"class", "style"},
    }

    class_allowlist = {
        "div": {
            "ql-code-block-container",
            "ql-code-block",
            "ql-token",
            "ql-ui",
            "ql-align-center",
            "ql-align-right",
            "ql-align-justify",
            "ql-indent-1",
            "ql-indent-2",
            "ql-indent-3",
            "ql-indent-4",
            "ql-indent-5",
            "ql-indent-6",
            "ql-indent-7",
            "ql-indent-8",
            "ql-indent-9",
            "ql-size-small",
            "ql-size-large",
            "ql-size-huge",
            "ql-video",
        },
        "span": {
            "ql-token",
            "hljs-keyword",
            "hljs-number",
            "hljs-string",
            "hljs-comment",
            "hljs-function",
            "hljs-title",
            "hljs-params",
            "hljs-variable",
            "hljs-operator",
            "hljs-builtin",
            "ql-ui",  # "ql-ui" added here
        },
        "p": {
            "ql-align-center",
            "ql-align-right",
            "ql-align-justify",
            "ql-indent-1",
            "ql-indent-2",
            "ql-indent-3",
            "ql-indent-4",
            "ql-indent-5",
            "ql-indent-6",
            "ql-indent-7",
            "ql-indent-8",
            "ql-indent-9",
        },
        "li": {
            "ql-align-center",
            "ql-align-right",
            "ql-align-justify",
            "ql-indent-1",
            "ql-indent-2",
            "ql-indent-3",
            "ql-indent-4",
            "ql-indent-5",
            "ql-indent-6",
            "ql-indent-7",
            "ql-indent-8",
            "ql-indent-9",
        },
        "iframe": {"ql-video"},
        "td": {"ql-align-center", "ql-align-right", "ql-align-justify"},
        "select": {"ql-ui"},
        "tr": {"ql-align-center", "ql-align-right", "ql-align-justify"},
    }

    # Transform the class allowlist into the structure expected by nh3.
    tag_attribute_values = {
        tag: {"class": classes} for tag, classes in class_allowlist.items()
    }

    url_schemes = {"http", "https", "mailto", "tel"}

    # Set the default link relationship attribute.
    link_rel = "noopener noreferrer"

    return nh3.clean(
        html,
        tags=allowed_tags,
        attributes=attributes,
        url_schemes=url_schemes,
        link_rel=link_rel,
        tag_attribute_values=tag_attribute_values,
        clean_content_tags=set(),
    )
