"""join_study_subject_study starts_on

Revision ID: 65a966f12056
Revises: f87512aa36db
Create Date: 2024-12-04 09:33:04.545484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a966f12056'
down_revision = 'f87512aa36db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_study_subject_study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_study_subject_study', schema=None) as batch_op:
        batch_op.drop_column('starts_on')

    # ### end Alembic commands ###
