# Copyright 2025 The Trustees of the University of Pennsylvania
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may]
# not use this file except in compliance with the License. You may obtain a
# copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""join_study_subject_study starts_on

Revision ID: 65a966f12056
Revises: f87512aa36db
Create Date: 2024-12-04 09:33:04.545484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65a966f12056'
down_revision = 'f87512aa36db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_study_subject_study', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('starts_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_study_subject_study', schema=None) as batch_op:
        batch_op.drop_column('starts_on')

    # ### end Alembic commands ###
