# Ditti Research Dashboard
# Copyright (C) 2025 the Trustees of the University of Pennsylvania
#
# Ditti Research Dashboard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Ditti Research Dashboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""join_study_subject_study starts_on

Revision ID: 65a966f12056
Revises: f87512aa36db
Create Date: 2024-12-04 09:33:04.545484

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65a966f12056"
down_revision = "f87512aa36db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "join_study_subject_study", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("starts_on", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "join_study_subject_study", schema=None
    ) as batch_op:
        batch_op.drop_column("starts_on")

    # ### end Alembic commands ###
