"""Non-unique phone numbers allowed

Revision ID: b7db6c8684bc
Revises: 1ea7fa443990
Create Date: 2025-09-12 11:43:17.374161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7db6c8684bc'
down_revision = '1ea7fa443990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('account_phone_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('account_phone_number_key'), ['phone_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
