"""Study Subjects

Revision ID: f267b6182686
Revises: 
Create Date: 2024-10-16 16:27:15.319137

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f267b6182686'
down_revision = 'a5cd64856d8f'
branch_labels = None
depends_on = 'a5cd64856d8f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('join_study_subject_api',
    sa.Column('study_subject_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_user_uuid', sa.String(), nullable=False),
    sa.Column('scope', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('access_key_uuid', sa.String(), nullable=True),
    sa.Column('refresh_key_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['study_subject_id'], ['study_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_subject_id', 'api_id'),
    sa.UniqueConstraint('access_key_uuid'),
    sa.UniqueConstraint('refresh_key_uuid')
    )
    op.create_table('join_study_subject_study',
    sa.Column('study_subject_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('did_consent', sa.Boolean(), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.ForeignKeyConstraint(['study_subject_id'], ['study_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_subject_id', 'study_id')
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_expiry_delta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consent_information', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('consent_information')
        batch_op.drop_column('default_expiry_delta')

    op.drop_table('join_study_subject_study')
    op.drop_table('join_study_subject_api')
    op.drop_table('study_subject')
    op.drop_table('api')
    # ### end Alembic commands ###